Part A &B

In [1]:
import numpy as np

In [4]:
states_day_0=np.loadtxt("input06.txt",delimiter=",")
states_day_0

array([1., 1., 3., 5., 1., 1., 1., 4., 1., 5., 1., 1., 1., 1., 1., 1., 1.,
       3., 1., 1., 1., 1., 2., 5., 1., 1., 1., 1., 1., 2., 1., 4., 1., 4.,
       1., 1., 1., 1., 1., 3., 1., 1., 5., 1., 1., 1., 4., 1., 1., 1., 4.,
       1., 1., 3., 5., 1., 1., 1., 1., 4., 1., 5., 4., 1., 1., 2., 3., 2.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 5., 1., 1., 1.,
       1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1., 1., 5., 1., 1., 1., 3.,
       4., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1., 4., 1., 1., 3., 1., 1.,
       3., 1., 1., 1., 1., 1., 3., 1., 5., 2., 3., 1., 2., 3., 1., 1., 2.,
       1., 2., 4., 5., 1., 5., 1., 4., 1., 1., 1., 1., 2., 1., 5., 1., 1.,
       1., 1., 1., 5., 1., 1., 3., 1., 1., 1., 1., 1., 1., 4., 1., 2., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 2., 1., 1., 1.,
       1., 2., 2., 1., 2., 1., 1., 1., 5., 5., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 2., 2., 1., 1., 4., 2., 1., 4., 1., 1., 1., 1.,
       1., 1., 1., 2., 1.

In [24]:
counts_per_state=np.zeros(9) # nr of fish in state: 0days, 1day, 2, 3, 4, 5, 6, 7, 8days

# start count
for idx in range(9):
    counts_per_state[idx]=np.count_nonzero(states_day_0==idx)
    
counts_per_state

array([  0., 222.,  24.,  19.,  17.,  18.,   0.,   0.,   0.])

In [25]:
def update(counts):
    new_counts=np.zeros_like(counts)
    for idx in range(8):
        new_counts[idx]=counts[idx+1]
    new_counts[8]=counts[0]
    new_counts[6]+=counts[0]
    return new_counts

In [26]:
for day in range(256):
    counts_per_state=update(counts_per_state)

In [27]:
counts_per_state

array([1.46712818e+11, 1.84289329e+11, 1.88786354e+11, 2.02168881e+11,
       2.42460747e+11, 2.25357050e+11, 2.98390113e+11, 1.19908149e+11,
       1.62750100e+11])

In [28]:
sum(counts_per_state)

1770823541496.0