Part A

In [1]:
import numpy as np

In [2]:
fn="input04.txt"

In [3]:
lines=[]
with open(fn,"r") as fin:
    text=fin.read()

In [4]:
thrown_numbers_text, boards_text=text.split("\n\n",1)
boards_text=boards_text.split("\n\n")
boards_text=[board_text.split("\n") for board_text in boards_text]

In [5]:
thrown_numbers=np.fromstring(thrown_numbers_text,sep=",",dtype=np.int)

In [6]:
thrown_numbers

array([ 0, 56, 39,  4, 52,  7, 73, 57, 65, 13,  3, 72, 69, 96, 18,  9, 49,
       83, 24, 31, 12, 64, 29, 21, 80, 71, 66, 95,  2, 62, 68, 46, 11, 33,
       74, 88, 17, 15,  5,  6, 98, 30, 51, 78, 76, 75, 28, 53, 87, 48, 20,
       22, 55, 86, 82, 90, 47, 19, 25,  1, 27, 60, 94, 38, 97, 58, 70, 10,
       43, 40, 89, 26, 34, 32, 23, 45, 50, 91, 61, 44, 35, 85, 63, 16, 99,
       92,  8, 36, 81, 84, 79, 37, 93, 67, 59, 54, 41, 77, 42, 14])

In [7]:
def one_board_text_to_array(board_text):
    array_rows=[]
    for line_text in board_text:
        array_rows.append(np.fromstring(line_text,sep=" ",dtype=np.int))
    return np.array(array_rows)

In [8]:
boards_text[0]

['63  5 10 69 57',
 '64 88 27 40 76',
 '59 20 58 90  6',
 '74 32 72 16 26',
 '50 17  7 93 94']

In [9]:
boards=[one_board_text_to_array(board_text) for board_text in boards_text]

In [10]:
boards

[array([[63,  5, 10, 69, 57],
        [64, 88, 27, 40, 76],
        [59, 20, 58, 90,  6],
        [74, 32, 72, 16, 26],
        [50, 17,  7, 93, 94]]),
 array([[92, 77, 33, 44, 14],
        [35, 25, 47, 91,  7],
        [99,  6, 56, 82, 10],
        [41, 93, 70,  5, 85],
        [81, 97, 58, 96, 29]]),
 array([[24, 53,  4,  8, 23],
        [ 0, 13, 48, 47, 83],
        [55, 56, 72, 50, 52],
        [82, 33, 58, 16, 11],
        [91,  7, 89,  9, 81]]),
 array([[86, 70, 16,  4, 34],
        [49, 69, 37, 78, 11],
        [22, 47, 59, 20, 38],
        [33, 82, 60, 63, 56],
        [18, 74, 36,  7, 99]]),
 array([[64, 45, 72, 86,  7],
        [34, 50, 94,  0, 85],
        [15, 69,  2, 26, 32],
        [62, 96, 41, 17, 78],
        [63,  5, 99, 79, 47]]),
 array([[62, 63, 24, 37, 50],
        [89, 80, 40, 41, 13],
        [32, 64, 95, 93, 66],
        [45,  3, 23, 78, 48],
        [60, 26, 31, 61, 99]]),
 array([[ 6, 63, 66, 67, 15],
        [33, 43, 62, 95, 89],
        [72, 61, 60,  2, 10]

In [11]:
trackers_status=[np.zeros((5,5)) for _ in range(len(boards))]

In [12]:
# start playing
def update_game(boards, trackers_status,nr):
    for board,tracker_status in zip(boards,trackers_status):
        hit=(board==nr)
        tracker_status[hit]=1
    
def check_for_winner(boards,trackers_status):
    for board,tracker_status in zip(boards,trackers_status):
        check_rows=np.sum(tracker_status,1)
        check_cols=np.sum(tracker_status,0)
        if max(check_cols)==board.shape[0] or max(check_rows)==board.shape[0]:
            return board, tracker_status

In [13]:
for nr in thrown_numbers:
    update_game(boards,trackers_status,nr)
    output=check_for_winner(boards,trackers_status)
    if output is not None:
        break

In [14]:
# the winning board
board,tracker_status=output

In [15]:
np.sum(board[tracker_status==0])*nr

45031

Part B

In [16]:
# reset game
trackers_status=[np.zeros((5,5)) for _ in range(len(boards))]

In [17]:
is_finished=np.zeros((len(boards)))

In [18]:
def update_who_finished(boards,trackers_status,is_finished):
    for idx,(board,tracker_status) in enumerate(zip(boards,trackers_status)):
        check_rows=np.sum(tracker_status,1)
        check_cols=np.sum(tracker_status,0)
        if max(check_cols)==board.shape[0] or max(check_rows)==board.shape[0]:
            is_finished[idx]=1
            

In [19]:
for nr in thrown_numbers:
    update_game(boards,trackers_status,nr)
    update_who_finished(boards,trackers_status,is_finished)
    if np.sum(is_finished==0)<=1:
        break


In [24]:
# this is the losing board
idx=int(np.where(is_finished==0)[0])

board=boards[idx]
tracker_status=trackers_status[idx]

In [25]:
# now let's keep playing until that board is finished as well
losing_board=[board]
losing_tracker_status=[tracker_status]

In [26]:
# a bit hacky: we start from the beginning again but doesn't matter
for nr in thrown_numbers:
    update_game(losing_board,losing_tracker_status,nr)
    output=check_for_winner(losing_board,losing_tracker_status)
    if output is not None:
        break

In [27]:
output

(array([[67, 51, 43, 89, 94],
        [ 4, 96, 50,  9,  8],
        [22, 87, 77, 38, 35],
        [39, 37, 17, 59, 32],
        [ 5, 25, 26, 83, 81]]),
 array([[0., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 0., 1., 0., 1.],
        [1., 1., 1., 1., 0.]]))

In [28]:
board,tracker_status=output

In [29]:
np.sum(board[tracker_status==0])*nr

2568